print('Enter the first number\t:')
num1=int(input())
print('Enter the second number\t:')
num2=int(input())
print('\nThe numbers entered are ',num1,' & ', num2)
(num1,num2)=(num2, num1)
print('\nThe numbers now are ', num1, ' & ', num2)